version: '3.8'
services:
    api:
        build: ./
        environment:
            - PORT=8000
            - DB_URL=mongodb://db/books_managements_dev
        ports:
            - 8000:8000
    db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - book_api_node:/data/db
volumes:
    book_api_node:
